version: "3.4"

services:
  # PostgreSQL container
  cmspostgres:
    image: postgres:11.5-alpine
    container_name: cmspostgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data/

  # Go application container
  app:
    build:
      context: .
      # target: serve
      target: dev
    container_name: vilna_cms
    restart: always
    ports:
      - "8080:8080"
      - "2345:2345"
    volumes:
      - ./:/go/src/vilnaCMS
    depends_on:
      - cmspostgres

  # Service for tracking containers logs
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

# Volume for storing db data
volumes:
  pgdata:
